In [42]:
import numpy as np
from numpy import array, float32
from scipy.linalg import ldl

In [8]:
cov = [[0.00630649,0.00631449,0.00631449,0.00596759,0.006031,  0.006031, ],
 [0.00631449,0.00630649,0.00631449,0.006031,  0.00596759, 0.006031  ],
 [0.00631449, 0.00631449, 0.00630649, 0.006031,   0.006031,   0.00596759],
 [0.00596759, 0.006031,   0.006031,   0.00700918, 0.00601316, 0.00601316],
 [0.006031,   0.00596759, 0.006031,   0.00601316, 0.00700918, 0.00601316],
 [0.006031,   0.006031,   0.00596759, 0.00601316, 0.00601316, 0.00700918]]


In [48]:
np.linalg.eigvals(cov)

array([ 3.70151444e-02, -1.19888816e-05,  9.55825628e-04,  1.00000888e-03,
       -1.19888816e-05,  1.00000888e-03])

In [18]:
ldl(cov)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 1.00126853,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 1.00126853,  0.50031693,  1.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.94626171, -3.48778196, -2.32469679,  1.        ,  0.        ,
          0.        ],
        [ 0.95631643,  4.43846804, -2.32469679,  0.07600734,  1.        ,
          0.        ],
        [ 0.95631643,  0.47785513,  5.60155321,  0.07600734,  0.07063831,
          1.        ]]),
 array([[ 6.30649000e-03,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00, -1.60101483e-05,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.20025355e-05,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.0000000

In [20]:
cov2 = np.eye(6,dtype=np.float32) * 0.001

cov2

array([[0.001, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.001, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.001, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.001, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.001]], dtype=float32)

In [21]:
np.linalg.cholesky(cov2)

array([[0.03162278, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03162278, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.03162278, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.03162278, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.03162278,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.03162278]], dtype=float32)

In [23]:
L, D, _ = ldl(cov2)

In [26]:
L@np.power(D,0.5)

array([[0.03162278, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03162278, 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.03162278, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.03162278, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.03162278,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.03162278]], dtype=float32)

In [32]:
processNoise = np.eye(6,dtype=np.float32)*0.001

np.linalg.cholesky(
cov-processNoise)

LinAlgError: Matrix is not positive definite

In [37]:
kalmanGain = np.array([[ 0.7021133 , -0.3010409 , -0.3010409 ],
       [-0.3010409 ,  0.7021133 , -0.3010409 ],
       [-0.3010409 , -0.3010409 ,  0.7021133 ],
       [ 0.03930594, -0.01685297, -0.01685297],
       [-0.01685297,  0.03930594, -0.01685297],
       [-0.01685297, -0.01685297,  0.03930594]], dtype=np.float32)
predictedMeasureCov = np.array([[0.00400946, 0.00300946, 0.00300946],
       [0.00300946, 0.00400946, 0.00300946],
       [0.00300946, 0.00300946, 0.00400946]], dtype=np.float32)
result = np.array([[ 7.0432783e-04, -3.0199040e-04, -3.0199034e-04,  3.9429917e-05,
        -1.6906128e-05, -1.6906126e-05],
       [-3.0199040e-04,  7.0432783e-04, -3.0199034e-04, -1.6906128e-05,
         3.9429917e-05, -1.6906126e-05],
       [-3.0199034e-04, -3.0199034e-04,  7.0432777e-04, -1.6906124e-05,
        -1.6906124e-05,  3.9429913e-05],
       [ 3.9429917e-05, -1.6906126e-05, -1.6906130e-05,  2.2073789e-06,
        -9.4644435e-07, -9.4644457e-07],
       [-1.6906126e-05,  3.9429917e-05, -1.6906130e-05, -9.4644435e-07,
         2.2073789e-06, -9.4644457e-07],
       [-1.6906128e-05, -1.6906128e-05,  3.9429917e-05, -9.4644446e-07,
        -9.4644446e-07,  2.2073789e-06]], dtype=np.float32)

In [39]:
kalmanGain@predictedMeasureCov@kalmanGain.T

array([[ 7.0432783e-04, -3.0199040e-04, -3.0199045e-04,  3.9429917e-05,
        -1.6906126e-05, -1.6906130e-05],
       [-3.0199040e-04,  7.0432783e-04, -3.0199045e-04, -1.6906126e-05,
         3.9429917e-05, -1.6906130e-05],
       [-3.0199043e-04, -3.0199043e-04,  7.0432789e-04, -1.6906128e-05,
        -1.6906128e-05,  3.9429920e-05],
       [ 3.9429920e-05, -1.6906130e-05, -1.6906130e-05,  2.2073789e-06,
        -9.4644446e-07, -9.4644446e-07],
       [-1.6906130e-05,  3.9429920e-05, -1.6906130e-05, -9.4644446e-07,
         2.2073789e-06, -9.4644446e-07],
       [-1.6906130e-05, -1.6906130e-05,  3.9429924e-05, -9.4644446e-07,
        -9.4644446e-07,  2.2073791e-06]], dtype=float32)

In [41]:
print(kalmanGain)
print(kalmanGain.T)

[[ 0.7021133  -0.3010409  -0.3010409 ]
 [-0.3010409   0.7021133  -0.3010409 ]
 [-0.3010409  -0.3010409   0.7021133 ]
 [ 0.03930594 -0.01685297 -0.01685297]
 [-0.01685297  0.03930594 -0.01685297]
 [-0.01685297 -0.01685297  0.03930594]]
[[ 0.7021133  -0.3010409  -0.3010409   0.03930594 -0.01685297 -0.01685297]
 [-0.3010409   0.7021133  -0.3010409  -0.01685297  0.03930594 -0.01685297]
 [-0.3010409  -0.3010409   0.7021133  -0.01685297 -0.01685297  0.03930594]]


In [43]:
predCov = array([[0.00701233, 0.00601233, 0.00601233, 0.00601233, 0.00601233,
        0.00601233],
       [0.00601233, 0.00701233, 0.00601233, 0.00601233, 0.00601233,
        0.00601233],
       [0.00601233, 0.00601233, 0.00701233, 0.00601233, 0.00601233,
        0.00601233],
       [0.00601233, 0.00601233, 0.00601233, 0.00701233, 0.00601233,
        0.00601233],
       [0.00601233, 0.00601233, 0.00601233, 0.00601233, 0.00701233,
        0.00601233],
       [0.00601233, 0.00601233, 0.00601233, 0.00601233, 0.00601233,
        0.00701233]], dtype=float32)

In [46]:
covCalc = predCov  - result

covCalc - cov

array([[ 1.51239742e-06, -1.69975897e-07, -1.69975897e-07,
         5.30996222e-06, -1.76386958e-06, -1.76386958e-06],
       [-1.69975897e-07,  1.51239742e-06, -1.69975897e-07,
        -1.76386958e-06,  5.30996222e-06, -1.76386958e-06],
       [-1.69975897e-07, -1.69975897e-07,  1.51239742e-06,
        -1.76386958e-06, -1.76386958e-06,  5.30996222e-06],
       [ 5.30996222e-06, -1.76386958e-06, -1.76386958e-06,
         9.42761130e-07,  1.16055455e-07,  1.16055455e-07],
       [-1.76386958e-06,  5.30996222e-06, -1.76386958e-06,
         1.16055455e-07,  9.42761130e-07,  1.16055455e-07],
       [-1.76386958e-06, -1.76386958e-06,  5.30996222e-06,
         1.16055455e-07,  1.16055455e-07,  9.42761130e-07]])

In [62]:
eigVals, eigVecs = np.linalg.eig(cov)

eigVals = np.diag(eigVals)

np.set_printoptions(precision=5)
np.set_printoptions(suppress=True)
print(eigVals)

[[ 0.03702  0.       0.       0.       0.       0.     ]
 [ 0.      -0.00001  0.       0.       0.       0.     ]
 [ 0.       0.       0.00096  0.       0.       0.     ]
 [ 0.       0.       0.       0.001    0.       0.     ]
 [ 0.       0.       0.       0.      -0.00001  0.     ]
 [ 0.       0.       0.       0.       0.       0.001  ]]


In [56]:
for i in range(eigVals.shape[0]):
    if(eigVals[i][i] < 0):
        eigVals[i][i] = 0

eigVals@eigVecs@eigVals.T

array([[0.03701514, 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.00095583, 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.00100001, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.00100001]])